/*

 */

package vista;

import modelo.CiclosDAO;
import controlador.Ciclos;
import modelo.CursosDAO;
import modelo.SeccionDAO;
import controlador.Cursos;
import controlador.Seccion;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author visitante
 */
public class ProcesoAsignacionAlumnos extends javax.swing.JInternalFrame {

    public void llenadoDeCombosCursos() {
      CursosDAO cursosDAO = new CursosDAO();
        List<Cursos> cursos = cursosDAO.select();
        combo2.addItem("Seleccione una opción");
        for (int i = 0; i < cursos.size(); i++) {
            combo2.addItem(cursos.get(i).getNombre_curso());
        
    }
        
        
}
    
    public void llenadoDeCombosCiclos() {
      CiclosDAO ciclosDAO = new CiclosDAO();
        List<Ciclos> ciclos = ciclosDAO.select();
        combo1.addItem("Seleccione una opción");
        for (int i = 0; i < ciclos.size(); i++) {
            combo1.addItem(ciclos.get(i).getNombre_ciclo());
        
    }
        
        
}
    public ProcesoAsignacionAlumnos() {
        initComponents();
        llenadoDeCombosCursos();

    }

    
        public String[]datos(String datos){
        String[] informacion = new String[5];
        if(datos.equalsIgnoreCase("Ciclo 1")){
            informacion[0]= "DESARROLLO HUMANO Y PROFESIONAL";
            informacion[1]= "METODOLOGÍA DE LA INVESTIGACIÓN";
            informacion[2]= "CONTABILIDAD I";
            informacion[3]= "INTRODUCCIÓN A LOS SISTEMAS DE CÓMPUTO";
            informacion[4]= "LÓGICA DE SISTEMAS";

        }
        if(datos.equalsIgnoreCase("Ciclo 2")){
            informacion[0]= "PRECÁLCULO";
            informacion[1]= "ÁLGEBRA LINEAL";
            informacion[2]= "ALGORITMOS";
            informacion[3]= "CONTABILIDAD II";
            informacion[4]= "MATEMÁTICA DISCRETA";
        }

      return informacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Secciones");
        setVisible(true);

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Ciclo 1", "Ciclo 2" }));
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(294, 484, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.combo1.getSelectedIndex()>0){
                this.combo2.setModel(new DefaultComboBoxModel(this.datos(this.combo1.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_combo1ItemStateChanged

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

/**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    // End of variables declaration//GEN-END:variables
}
