/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.subAlumnosDAO;
import controlador.subAlumnos;
import controlador.clsBitacora;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import controlador.clsUsuarioConectado;
import modelo.Conexion;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author visitante
 */
public class subProcesoAlumnos extends javax.swing.JInternalFrame {
    int codigoAplicacion = 2015;

    clsBitacora Auditoria = new clsBitacora();
    public void llenadoDeCombos() {
       /*EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.select();
        cbox_empleado.addItem("Seleccione una opción");
        for (int i = 0; i < empleados.size(); i++) {
            cbox_empleado.addItem(empleados.get(i).getNombreEmpleado());
        }*/
    }

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Carnet");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        modelo.addColumn("Estatus");
        subAlumnosDAO alumnoDAO = new subAlumnosDAO();
        List<subAlumnos> alumnos = alumnoDAO.select();
        tablaSubAlumno.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < alumnos.size(); i++) {
            dato[0] = alumnos.get(i).getCertificado();
            dato[1] = alumnos.get(i).getNombre_subalumno();
            dato[2] = alumnos.get(i).getDireccion_alumno();
            dato[3] = alumnos.get(i).getTelefono_alumno();
            dato[4] = alumnos.get(i).getEmail_alumno();
            dato[5] = alumnos.get(i).getEstatus_alumno();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarAlumnos() {
        subAlumnos alumnoAConsultar = new subAlumnos();
        subAlumnosDAO alumnoDAO = new subAlumnosDAO();
        alumnoAConsultar.setCertificado((txtbuscado.getText()));
        alumnoAConsultar = alumnoDAO.query(alumnoAConsultar);
        txtCarnet.setText(alumnoAConsultar.getCertificado());
        txtNombre.setText(alumnoAConsultar.getNombre_subalumno());
        txtDireccion.setText(alumnoAConsultar.getDireccion_alumno());
        txtTelefono.setText(alumnoAConsultar.getTelefono_alumno());
        txtEmail.setText(alumnoAConsultar.getEmail_alumno());
        txtEstatus.setText(alumnoAConsultar.getEstatus_alumno());
    }

    public subProcesoAlumnos() {
        initComponents();
        llenadoDeTablas();
        llenadoDeCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        bgcertificado = new javax.swing.ButtonGroup();
        bgtitulo = new javax.swing.ButtonGroup();
        bgevaluacion = new javax.swing.ButtonGroup();
        bgfoto = new javax.swing.ButtonGroup();
        bgformulario = new javax.swing.ButtonGroup();
        bgdpi = new javax.swing.ButtonGroup();
        bgcomprobante = new javax.swing.ButtonGroup();
        btnRegistrar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSubAlumno = new javax.swing.JTable();
        lb = new javax.swing.JLabel();
        bsinentregar = new javax.swing.JRadioButton();
        bambos = new javax.swing.JRadioButton();
        bno = new javax.swing.JRadioButton();
        jcbAlumno = new javax.swing.JComboBox<>();
        bsinellos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        bfisico = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        bdigital = new javax.swing.JRadioButton();
        brealizada = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        bnotiene = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        bambosd = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        binscrito = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        bfaltantes = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        bnoinscrito = new javax.swing.JRadioButton();
        bentregado = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        bsi = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SubProceso Alumnos");
        setVisible(true);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("Proceso Alumnos");

        tablaSubAlumno.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaSubAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Certificado", "Titulo", "Ev.ubic", "Foto", "DPI", "Formulario", "Comprobante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSubAlumno);

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");

        bgcertificado.add(bsinentregar);
        bsinentregar.setText("sin entegar");

        bgtitulo.add(bambos);
        bambos.setText("ambos");

        bgcomprobante.add(bno);
        bno.setText("no");

        jcbAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar nombre de alumno" }));
        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });

        bgtitulo.add(bsinellos);
        bsinellos.setText("sin ellos");

        jLabel1.setText("Nombre del Alumno ");

        bgfoto.add(bfisico);
        bfisico.setText("fisico");

        jLabel2.setText("Certificado de Graduacion:");

        bgfoto.add(bdigital);
        bdigital.setText("digital");

        bgevaluacion.add(brealizada);
        brealizada.setText("Realizada");

        jLabel3.setText("Evaluacion de ubicacion");

        bgevaluacion.add(bnotiene);
        bnotiene.setText("no tiene");

        jLabel4.setText("DPI con copia");

        bgdpi.add(bambosd);
        bambosd.setText("ambos");

        jLabel5.setText(" titulo original y copia");

        bgformulario.add(binscrito);
        binscrito.setText("inscrito");

        jLabel6.setText("Foto tamaño cedula");

        bgdpi.add(bfaltantes);
        bfaltantes.setText("Faltantes");

        jLabel7.setText("Comprobante inscripción");

        bgformulario.add(bnoinscrito);
        bnoinscrito.setText("no Inscrito");

        bgcertificado.add(bentregado);
        bentregado.setText("entregado");
        bentregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentregadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Formulario de inscripcion");

        bgcomprobante.add(bsi);
        bsi.setText("si");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bentregado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bsinentregar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(brealizada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnotiene))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bambosd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bfaltantes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsi)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bno))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bambos)
                                .addGap(18, 18, 18)
                                .addComponent(bsinellos))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bfisico)
                                .addGap(18, 18, 18)
                                .addComponent(bdigital))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(binscrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bnoinscrito)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1)
                        .addGap(294, 294, 294))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bsinentregar)
                                    .addComponent(bentregado)
                                    .addComponent(bambos)
                                    .addComponent(bsinellos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bfisico)
                                    .addComponent(bdigital)
                                    .addComponent(brealizada)
                                    .addComponent(bnotiene))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bambosd)
                                    .addComponent(binscrito)
                                    .addComponent(bfaltantes)
                                    .addComponent(bnoinscrito))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bsi)
                                    .addComponent(bno))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificar))))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        bgcertificado.add(bentregado);
        bgcertificado.add(bsinentregar);
        bgtitulo.add(bambos);
        bgtitulo.add(bsinellos);
        bgevaluacion.add();
        
        subAlumnosDAO alumnoDAO = new subAlumnosDAO();
        subAlumnos alumnoAInsertar = new subAlumnos();
        alumnoAInsertar.setCertificado(txtCarnet.getText());
        alumnoAInsertar.setNombre_subalumno(txtNombre.getText());
        alumnoAInsertar.setDireccion_alumno(txtDireccion.getText());
        alumnoAInsertar.setTelefono_alumno(txtTelefono.getText());
        alumnoAInsertar.setEmail_alumno(txtEmail.getText());
        alumnoAInsertar.setEstatus_alumno(txtEstatus.getText());
        alumnoDAO.insert(alumnoAInsertar);
        llenadoDeTablas();
        Auditoria.setIngresarBitacora(clsUsuarioConectado.getIdUsuario(), codigoAplicacion, "INS");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
        subAlumnosDAO alumnosDAO = new subAlumnosDAO();
        List<subAlumnos> alumnos = alumnosDAO.select();
        for (subAlumnos alumno : alumnos) {
            String item = alumno.getCertificado() + "      " + alumno.getNombre_subalumno();
            jcbAlumno.addItem(item);
        }
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    private void bentregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bentregadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //        // TODO add your handling code here:
        subAlumnosDAO alumnoDAO = new subAlumnosDAO();
        subAlumnos alumnoAActualizar = new subAlumnos();
        alumnoAActualizar.setCertificado(txtbuscado.getText());
        alumnoAActualizar.setNombre_subalumno(txtNombre.getText());
        alumnoAActualizar.setDireccion_alumno(txtDireccion.getText());
        alumnoAActualizar.setTelefono_alumno(txtTelefono.getText());
        alumnoAActualizar.setEmail_alumno(txtEmail.getText());
        alumnoAActualizar.setEstatus_alumno(txtEstatus.getText());
        alumnoDAO.update(alumnoAActualizar);
        Auditoria.setIngresarBitacora(clsUsuarioConectado.getIdUsuario(), codigoAplicacion, "UPD");
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bambos;
    private javax.swing.JRadioButton bambosd;
    private javax.swing.JRadioButton bdigital;
    private javax.swing.JRadioButton bentregado;
    private javax.swing.JRadioButton bfaltantes;
    private javax.swing.JRadioButton bfisico;
    private javax.swing.ButtonGroup bgcertificado;
    private javax.swing.ButtonGroup bgcomprobante;
    private javax.swing.ButtonGroup bgdpi;
    private javax.swing.ButtonGroup bgevaluacion;
    private javax.swing.ButtonGroup bgformulario;
    private javax.swing.ButtonGroup bgfoto;
    private javax.swing.ButtonGroup bgtitulo;
    private javax.swing.JRadioButton binscrito;
    private javax.swing.JRadioButton bno;
    private javax.swing.JRadioButton bnoinscrito;
    private javax.swing.JRadioButton bnotiene;
    private javax.swing.JRadioButton brealizada;
    private javax.swing.JRadioButton bsi;
    private javax.swing.JRadioButton bsinellos;
    private javax.swing.JRadioButton bsinentregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbAlumno;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaSubAlumno;
    // End of variables declaration//GEN-END:variables
}
