use siu;
INSERT INTO ciclos(codigo_ciclo, nombre_ciclo, estatus_ciclo) VALUES
(101, "1 Ciclo", "A"),
(102, "2 Ciclo", "A"),
(103, "3 Ciclo", "A"),
(104, "4 Ciclo", "A"),
(105, "5 Ciclo", "A"),
(106, "6 Ciclo", "A"),
(107, "7 Ciclo", "A"),
(108, "8 Ciclo", "A"),
(109, "9 Ciclo", "A"),
(110, "10 Ciclo", "A")
;

INSERT INTO cursos(codigo_curso, nombre_curso, estatus_curso) VALUES
("101", "Desarrollo Humano y Profesional", "A"),
("102", "Metodologia de la Investigacion", "A"),
("103", "Contabilidad I", "A"),
("104", "Introduccion a los Sistemas de Computo", "A"),
("105", "Logica de Sistemas", "A"),
("106", "Precalculo", "A"),
("107", "Algebra Lineal", "A"),
("108", "Algoritmos", "A"),
("109", "Contabilidad II", "A"),
("110", "Matematica Discreta", "A"),
("111", "Fisica I", "A"),
("112", "Programacion I", "A"),
("113", "Calculo I", "A"),
("114", "Proceso Administrativo ", "A"),
("115", "Derecho Informatico", "A"),
("116", "Microeconomía", "A"),
("117", "Programacion II", "A"),
("118", "Calculo II", "A"),
("119", "Estadistica I", "A"),
("120", "Fisica II", "A"),
("121", "Metodos Numericos", "A"),
("122", "Programacion III", "A"),
("123", "Emprendedores de Negocios", "A"),
("124", "Electronica Analogica", "A"),
("125", "Estadistica II", "A"),
("126", "Investigacion de Operaciones", "A"),
("127", "Bases de Datos I", "A"),
("128", "Automatas y Lenguajes Formales", "A"),
("129", "Sistemas Operativos I", "A"),
("130", "Electronica Digital", "A"),
("131", "Bases de Datos II", "A"),
("132", "Analisis de Sistemas ", "A"),
("133", "Sistemas Operativos II", "A"),
("134", "Arquitectura de Computadoras I", "A"),
("135", "Compiladores", "A"),
("136", "Desarrollo Web", "A"),
("137", "Analisis de Sistemas II", "A"),
("138", "Redes de Computadoras I", "A"),
("139", "Etica profesional", "A"),
("140", "Arquitactura de Computadoras II", "A"),
("141", "Administracion de Tecnologias de Informacion", "A"),
("142", "Ingenieria de Software", "A"),
("143", "Proyecto de Graduacion I", "A"),
("144", "Redes de Computadoras II", "A"),
("145", "Inteligencia Artificial", "A"),
("146", "Telecomunicaciones", "A"),
("147", "Seminario de Tecnologías de Informacion", "A"),
("148", "Aseguramiento de la Calidad de Software", "A"),
("149", "Proyecto de Graduacion II", "A"),
("150", "Seguridad y Auditoria de Sistemas", "A");